add_newline = false

[line_break]
disabled = true

[hostname]
disabled = true
ssh_only = true

[cmd_duration]
min_time = 10000
show_milliseconds = false
format = "[$duration]($style)"

[kubernetes]
disabled = false

[directory]
truncation_length = 2
