#! /usr/bin/env bash
# vim:foldmethod=marker
# general config {{{
bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2e2e2e"
bspc config active_border_color "#2e2e2e"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"
bspc config urgent_border_color "#dd2727"

bspc config focus_follows_pointer true
# }}}
# Hostname dependent config {{{
if [[ $(hostname) == 'purity' ]]; then
	bspc monitor HDMI-A-0 -d I II III
	bspc monitor DisplayPort-0 -d IV V VI VII
	bspc monitor DisplayPort-1 -d VIII IX X

	bspc monitor HDMI-A-0 -g 1920x1080+0+0
	bspc monitor DisplayPort-0 -g 2560x1440+1920+0
	bspc monitor DisplayPort-1 -g 1920x1080+4480+0

	# if ! pgrep "urxvtd" > /dev/null 2>&1 ; then
	# 	urxvtd -q -o -f
	# fi

	xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DisplayPort-1 --mode 1920x1080 --pos 4480x0 --rotate normal --output DVI-I-0 --off --output DP-1 --off --output DP-0 --off &
else
	bspc monitor DP-2 -d I II III IV V
	bspc monitor HDMI-1 -d VI VII VIII IX X

	bspc monitor DP-2 -g 1920x1200+0+0
	bspc monitor HDMI-1 -g 1920x1200+1920+0

	xrandr --output DP-2 --primary --mode 1920x1200 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1200 --pos 1920x0 --rotate normal &
	# if ! pgrep "urxvt256c-mld" > /dev/null 2>&1 ; then
	# 	urxvt256c-mld -q -o -f
	# fi
fi
# }}}
# rules {{{
bspc rule -r "*"
bspc rule -a discord desktop=^2
bspc rule -a Steam desktop=^5
bspc rule -a "Pavucontrol":pavucontrol state=floating
bspc rule -a mpv state=floating
bspc rule -a "Sxiv":sxiv state=floating
bspc rule -a mpv floating=on
bspc rule -a '*:scratchpad' sticky=on state=floating center=true rectangle=1600x1000+0+0
# }}}
# autoexec {{{
killall -q sxhkd; sxhkd &
$HOME/.config/polybar/launchbspwm.sh &
setxkbmap -v no &
feh --bg-scale $HOME/.config/wall.png &
xrdb $HOME/.Xresources
xsetroot -cursor_name left_ptr
if ! pgrep "picom" > /dev/null 2>&1 ; then
	picom -b &
fi
# }}}
